config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'messages#index'
  resources :messages
  resources :messages do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message, optional: true
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments
  mount_uploader :image, ImageUploader
  mount_uploader :pic, ImageUploader

  def self.search(search)
    if search != ""
      Message.where('keyword LIKE(?)', "%#{search}%")
    else
      Message.all
    end
  end
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   # deviseコントローラーにストロングパラメータを追加する          
   before_action :configure_permitted_parameters, if: :devise_controller?

   protected
   def configure_permitted_parameters
     # サインアップ時にnameのストロングパラメータを追加
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     # アカウント編集の時にnameとprofileのストロングパラメータを追加
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/messages/#{comment.message.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :go_index, except: [:index, :show, :search]
  
  def index
    @messages = Message.includes(:user).order("created_at DESC")
  end

  def new
    @message = Message.new
  end

  def create
    Message.create(message_params)
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
  end

  def edit
    @mesage = Message.find(params[:id])
  end

  def update
    message = Message.find(params[:id])
    message = update(message_params)
  end

  def show
    @message = Message.find(params[:id])
    @comment = Comment.new
    @comments = @message.comments.includes(:user)

    # 参考サイト1
    # https://sadah.github.io/rails-training/ja/004_comments.html
    # @message = Message.includes(:user).find(params[:id])
    # @comments = @message.comments.includes(:user).all
    # @comment = @message.comments.build(user_id: current_user.id) if current_user


    # 参考サイト2
    # @comment = @message.comments.create(comment.params)
    # https://qiita.com/nojinoji/items/2034764897c6e91ef982
  end

  def search
    @messages = Message.search(params[:keyword])
  end

  private
  def message_params
    params.require(:message).permit(:grade, :subject, :text, :image, :user_id, :detail, :pic).merge(user_id: current_user.id)
  end

  def go_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @user = user.name
    @messages = user.messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pritea
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.header
      %p
        %a.header-logo{href:"/"}
          %img{src:"assets/logo.png", :height => "140px", :width => "420px",}

      .header__ber
        .header__ber--left
          %h2
            みんなのおすすめプリントで,
            %br>/
            楽しくわかりやすい授業を ^_^
        .header__ber--right
          - if user_signed_in?
            .logined
              %span.current_user
                = current_user.name
              %ul.user__info
                %li
                  = link_to "ログアウト", destroy_user_session_path,method: :delete, class: "header-post"
                  = link_to "マイページ", "/users/#{current_user.id}", class:"header-post" 
                  = link_to "投稿する", new_message_path, class: "header-post"
          - else
            .no_login
              = link_to "ログイン", new_user_session_path, class: "header-post"
              = link_to "新規登録", new_user_registration_path, class: "header-post"
            
    = yield
    %footer.footer
      %p
        %a.footer-logo{href:"/"}
          %img{src:"assets/logo.png", :height => "70px", :width => "210px",}
      %p
        @ 2020 ea2ne

app/views/messages/_head.html.haml
-# .header
-#   %p
-#     %a.header-logo{href:"/"}
-#       %img{src:"assets/logo.png", :height => "140px", :width => "420px",}

-#   .header__ber
-#     .header__ber--left
-#       %h2
-#         みんなのおすすめプリントで,
-#         %br>/
-#         楽しくわかりやすい授業を ^_^
-#     .header__ber--right
-#       - if user_signed_in?
-#         .logined
-#           %span.current_user
-#             = current_user.name
-#           %ul.user__info
-#             %li
-#               = link_to "ログアウト", destroy_user_session_path,method: :delete, class: "header-post"
-#               = link_to "マイページ", "/users/#{current_user.id}", class:"header-post" 
-#               = link_to "投稿する", new_message_path, class: "header-post"
-#       - else
-#         .no_login
-#           = link_to "ログイン", new_user_session_path, class: "header-post"
-#           = link_to "新規登録", new_user_registration_path, class: "header-post"

app/views/messages/_left.html.haml
.left
  .info
    .search
      = form_with(url: messages_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
        = form.submit "検索", class: "search-btn"

    .info__popular
      <br>人気
    .info__subject
      学年・教科<br>
    .image_test
      = icon("fas", "book")  
      -# = fa_icon 'edit'
      %i.fa.fa-cog
      = link_to "https://www.facebook.com/", class: "facebook" do
        = icon('fab', 'facebook-square')
      = link_to "https://www.facebook.com/", class: "facebook" do
        = icon('fab', 'facebook-square')
        Facebook<br>
      = link_to "https://twitter.com/", class: "twitter" do
        = icon('fab', 'twitter')
        Twitter<br>
      = link_to "https://www.instagram.com/", class: "instagram" do
        = icon('fab', 'instagram')
        Instagram

app/views/messages/_right.html.haml
.right
  .post
    .post__detail
      - @messages.each do |message|
        .more
          = icon("fas", "book")  
          %i.fa.fa-cog
          -# %span=image_tag 'fal fa-list-ul'
          %span=image_tag 'arrow_top.png'
          %ul.more_list
            %li
              =link_to '詳細', message_path(message.id), method: :get
            - if user_signed_in? && current_user.id == message.user_id
              %li
              =link_to '編集', edit_message_path(message.id), method: :get
              %li
              =link_to '削除', message_path(message.id), method: :delete
        作者
        %span.name
          %a{href: "/users/#{message.user.id}"}
            = message.user.name
        <br>
        学年
        %span.grade
          = message.grade
        <br>
        科目
        %span.subject
          = message.subject
        <br>
        題名
        %span.text
          = message.text
        <br>
        詳細
        %span.text
          = message.detail
        <br>
    .post__form
      .search--icon
        <i class="fas fa-search"></i>
        <i class="fas fa-file-download"></i>

    -# .right__pic
          -# = @group.name
        -# .left-2
          -# - @group.users.each do |u|
            -# = u.name

      -# .right__pic--right
      -#   .edit
          -# = link_to edit_group_path(@group) do
            edit
    .MessageField
      - @messages.each do |message|
        .content_post{style:"background-image:url(#{message.image});"}

  .bottom
    -# = form_with model: @message, html: {class: "Form"}, local: true do |f|
      .form
        .form_contents
          = f.text_field :content, class: 'Form__inputContent', placeholder: 'type a message'
          = f.label :image, class: 'Form__inputImage' do
            = icon('far', 'image', class: 'Form__icon')
            = f.file_field :image, class: 'Hidden'
          = f.submit 'Send', class: 'Form__submit'

app/views/messages/destroy.html.haml
.contents
  .destroy
    %h3 削除が完了しました。
    %a.btn{href:"/"}一覧へ戻る

app/views/messages/edit.html.haml
.content
  .container
    = form_with(model: @message, local: true, class: :form_box) do |f|
      %h3 編集する
      = f.text_field :grade, placeholder: "学年", class: "detail-s"
      = f.text_field :subject, placeholder: "科目", class: "detail-s"
      = f.text_field :text, placeholder: "題名", class: "detail-m"
      = f.text_area :detail, placeholder: "説明", rows: "10", class: "detail-l"
      -# = f.text_field :image, placeholder: "Image Url", class: "text-center", id: "test-id"
      = f.file_field :image, placeholder: "画像ファイルを選択", class: "detail-m"
      = f.submit "送信" ,class: "submit-new"

app/views/messages/index.html.haml
.wrapper
  -# = render "head"
  = render "left"
  = render "right"

app/views/messages/new.html.haml
.content
  .container
    = form_with(model: @message, local: true, class: :form_box) do |f|
      %h3 投稿する
      = f.text_field :grade, placeholder: "学年", class: "detail-s"
      = f.text_field :subject, placeholder: "科目", class: "detail-s"
      = f.text_field :text, placeholder: "題名", class: "detail-m"
      = f.text_area :detail, placeholder: "説明", rows: "10", class: "detail-l"
      -# = f.text_field :image, placeholder: "Image Url", class: "text-center", id: "test-id"
      = f.file_field :image, placeholder: "画像ファイルを選択", class: "detail-m"
      = f.submit "送信" ,class: "submit-new"

app/views/messages/search.html.haml
.search-rst
  = form_with(url: messages_path, local: true, method: :get, class: "search-form") do |form|
  = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  =form.submit "検索", class: "search-btn"
.contents
  - @messages.each do |message|
    =render partial: "message", locals: { message: message}

app/views/messages/show.html.haml
.contents
  .more_show
    %span= image_tag 'arrow_top.png'
    %ul.more_list
      - if user_signed_in? && current_user.id == @message.user_id
        %li
        =link_to '編集', edit_message_path(@message.id), method: :get
        %li
        =link_to '削除', message_path(@message.id), method: :delete
    作者
    %span.name
      %a{href: "users/#{@message.user.id}"}
        = @message.user.name
    <br>
    学年
    %span.grade
      = @message.grade
    <br>
    科目
    %span.subject
      = @message.subject
    <br>
    題名
    %span.text
      = @message.text
    <br>
    詳細
    %span.text
      = @message.detail
  .content_show{style: "background-image: url(#{@message.image});"}
.comment_container
- if current_user
  = form_with(model: [@message, @comment], local: true) do |form|
    = form.text_area :comment, placeholder: "コメントする", rows: "2", class: "comment-form"
    = form.submit "送信"
- else
  %strong
    %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
.comments
  %h4 ＜コメント一覧＞
  - if @comments
    - @comments.each do |comment|
      %p
        %strong
          = link_to comment.user.name, "/users/#{comment.user_id}"
          ：
          = comment.comment

app/views/messages/update.html.haml
.contents.row
  .success
    %h3 更新が完了しました。
    %a.btn{href: "/"} 投稿一覧へ戻る

app/views/users/show.html.haml
.mypage
  %p.show__name
    = @user
    さんの投稿一覧
  .mypage__show
    .mypage__show--box
      - @messages.each do |message|
        %p= message.text
        %span.grade= message.grade
        %span.subject= message.subject
        %span.detail= message.detail
        .content_post{style: "background-image: url(#{message.image});"}